# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.api.servicecontrol.v1 import quota_controller_pb2 as google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2


class QuotaControllerStub(object):
  """[Google Quota Control API](/service-control/overview)

  Allows clients to allocate and release quota against a [managed
  service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AllocateQuota = channel.unary_unary(
        '/google.api.servicecontrol.v1.QuotaController/AllocateQuota',
        request_serializer=google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaRequest.SerializeToString,
        response_deserializer=google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaResponse.FromString,
        )


class QuotaControllerServicer(object):
  """[Google Quota Control API](/service-control/overview)

  Allows clients to allocate and release quota against a [managed
  service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
  """

  def AllocateQuota(self, request, context):
    """Attempts to allocate quota for the specified consumer. It should be called
    before the operation is executed.

    This method requires the `servicemanagement.services.quota`
    permission on the specified service. For more information, see
    [Cloud IAM](https://cloud.google.com/iam).

    **NOTE:** The client **must** fail-open on server errors `INTERNAL`,
    `UNKNOWN`, `DEADLINE_EXCEEDED`, and `UNAVAILABLE`. To ensure system
    reliability, the server may inject these errors to prohibit any hard
    dependency on the quota functionality.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QuotaControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AllocateQuota': grpc.unary_unary_rpc_method_handler(
          servicer.AllocateQuota,
          request_deserializer=google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaRequest.FromString,
          response_serializer=google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.api.servicecontrol.v1.QuotaController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
