# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/services/detail_placement_view_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.ads.googleads.v1.resources import detail_placement_view_pb2 as google_dot_ads_dot_googleads_dot_v1_dot_resources_dot_detail__placement__view__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/ads/googleads/v1/services/detail_placement_view_service.proto',
  package='google.ads.googleads.v1.services',
  syntax='proto3',
  serialized_options=b'\n$com.google.ads.googleads.v1.servicesB\037DetailPlacementViewServiceProtoP\001ZHgoogle.golang.org/genproto/googleapis/ads/googleads/v1/services;services\242\002\003GAA\252\002 Google.Ads.GoogleAds.V1.Services\312\002 Google\\Ads\\GoogleAds\\V1\\Services\352\002$Google::Ads::GoogleAds::V1::Services',
  serialized_pb=b'\nDgoogle/ads/googleads/v1/services/detail_placement_view_service.proto\x12 google.ads.googleads.v1.services\x1a=google/ads/googleads/v1/resources/detail_placement_view.proto\x1a\x1cgoogle/api/annotations.proto\"6\n\x1dGetDetailPlacementViewRequest\x12\x15\n\rresource_name\x18\x01 \x01(\t2\xf0\x01\n\x1a\x44\x65tailPlacementViewService\x12\xd1\x01\n\x16GetDetailPlacementView\x12?.google.ads.googleads.v1.services.GetDetailPlacementViewRequest\x1a\x36.google.ads.googleads.v1.resources.DetailPlacementView\">\x82\xd3\xe4\x93\x02\x38\x12\x36/v1/{resource_name=customers/*/detailPlacementViews/*}B\x86\x02\n$com.google.ads.googleads.v1.servicesB\x1f\x44\x65tailPlacementViewServiceProtoP\x01ZHgoogle.golang.org/genproto/googleapis/ads/googleads/v1/services;services\xa2\x02\x03GAA\xaa\x02 Google.Ads.GoogleAds.V1.Services\xca\x02 Google\\Ads\\GoogleAds\\V1\\Services\xea\x02$Google::Ads::GoogleAds::V1::Servicesb\x06proto3'
  ,
  dependencies=[google_dot_ads_dot_googleads_dot_v1_dot_resources_dot_detail__placement__view__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_GETDETAILPLACEMENTVIEWREQUEST = _descriptor.Descriptor(
  name='GetDetailPlacementViewRequest',
  full_name='google.ads.googleads.v1.services.GetDetailPlacementViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_name', full_name='google.ads.googleads.v1.services.GetDetailPlacementViewRequest.resource_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=253,
)

DESCRIPTOR.message_types_by_name['GetDetailPlacementViewRequest'] = _GETDETAILPLACEMENTVIEWREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDetailPlacementViewRequest = _reflection.GeneratedProtocolMessageType('GetDetailPlacementViewRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDETAILPLACEMENTVIEWREQUEST,
  '__module__' : 'google.ads.googleads.v1.services.detail_placement_view_service_pb2'
  # @@protoc_insertion_point(class_scope:google.ads.googleads.v1.services.GetDetailPlacementViewRequest)
  })
_sym_db.RegisterMessage(GetDetailPlacementViewRequest)


DESCRIPTOR._options = None

_DETAILPLACEMENTVIEWSERVICE = _descriptor.ServiceDescriptor(
  name='DetailPlacementViewService',
  full_name='google.ads.googleads.v1.services.DetailPlacementViewService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=256,
  serialized_end=496,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDetailPlacementView',
    full_name='google.ads.googleads.v1.services.DetailPlacementViewService.GetDetailPlacementView',
    index=0,
    containing_service=None,
    input_type=_GETDETAILPLACEMENTVIEWREQUEST,
    output_type=google_dot_ads_dot_googleads_dot_v1_dot_resources_dot_detail__placement__view__pb2._DETAILPLACEMENTVIEW,
    serialized_options=b'\202\323\344\223\0028\0226/v1/{resource_name=customers/*/detailPlacementViews/*}',
  ),
])
_sym_db.RegisterServiceDescriptor(_DETAILPLACEMENTVIEWSERVICE)

DESCRIPTOR.services_by_name['DetailPlacementViewService'] = _DETAILPLACEMENTVIEWSERVICE

# @@protoc_insertion_point(module_scope)
