# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/services/product_bidding_category_constant_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.ads.googleads.v1.resources import product_bidding_category_constant_pb2 as google_dot_ads_dot_googleads_dot_v1_dot_resources_dot_product__bidding__category__constant__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/ads/googleads/v1/services/product_bidding_category_constant_service.proto',
  package='google.ads.googleads.v1.services',
  syntax='proto3',
  serialized_options=b'\n$com.google.ads.googleads.v1.servicesB*ProductBiddingCategoryConstantServiceProtoP\001ZHgoogle.golang.org/genproto/googleapis/ads/googleads/v1/services;services\242\002\003GAA\252\002 Google.Ads.GoogleAds.V1.Services\312\002 Google\\Ads\\GoogleAds\\V1\\Services\352\002$Google::Ads::GoogleAds::V1::Services',
  serialized_pb=b'\nPgoogle/ads/googleads/v1/services/product_bidding_category_constant_service.proto\x12 google.ads.googleads.v1.services\x1aIgoogle/ads/googleads/v1/resources/product_bidding_category_constant.proto\x1a\x1cgoogle/api/annotations.proto\"A\n(GetProductBiddingCategoryConstantRequest\x12\x15\n\rresource_name\x18\x01 \x01(\t2\x9b\x02\n%ProductBiddingCategoryConstantService\x12\xf1\x01\n!GetProductBiddingCategoryConstant\x12J.google.ads.googleads.v1.services.GetProductBiddingCategoryConstantRequest\x1a\x41.google.ads.googleads.v1.resources.ProductBiddingCategoryConstant\"=\x82\xd3\xe4\x93\x02\x37\x12\x35/v1/{resource_name=productBiddingCategoryConstants/*}B\x91\x02\n$com.google.ads.googleads.v1.servicesB*ProductBiddingCategoryConstantServiceProtoP\x01ZHgoogle.golang.org/genproto/googleapis/ads/googleads/v1/services;services\xa2\x02\x03GAA\xaa\x02 Google.Ads.GoogleAds.V1.Services\xca\x02 Google\\Ads\\GoogleAds\\V1\\Services\xea\x02$Google::Ads::GoogleAds::V1::Servicesb\x06proto3'
  ,
  dependencies=[google_dot_ads_dot_googleads_dot_v1_dot_resources_dot_product__bidding__category__constant__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_GETPRODUCTBIDDINGCATEGORYCONSTANTREQUEST = _descriptor.Descriptor(
  name='GetProductBiddingCategoryConstantRequest',
  full_name='google.ads.googleads.v1.services.GetProductBiddingCategoryConstantRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_name', full_name='google.ads.googleads.v1.services.GetProductBiddingCategoryConstantRequest.resource_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=288,
)

DESCRIPTOR.message_types_by_name['GetProductBiddingCategoryConstantRequest'] = _GETPRODUCTBIDDINGCATEGORYCONSTANTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetProductBiddingCategoryConstantRequest = _reflection.GeneratedProtocolMessageType('GetProductBiddingCategoryConstantRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTBIDDINGCATEGORYCONSTANTREQUEST,
  '__module__' : 'google.ads.googleads.v1.services.product_bidding_category_constant_service_pb2'
  # @@protoc_insertion_point(class_scope:google.ads.googleads.v1.services.GetProductBiddingCategoryConstantRequest)
  })
_sym_db.RegisterMessage(GetProductBiddingCategoryConstantRequest)


DESCRIPTOR._options = None

_PRODUCTBIDDINGCATEGORYCONSTANTSERVICE = _descriptor.ServiceDescriptor(
  name='ProductBiddingCategoryConstantService',
  full_name='google.ads.googleads.v1.services.ProductBiddingCategoryConstantService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=291,
  serialized_end=574,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProductBiddingCategoryConstant',
    full_name='google.ads.googleads.v1.services.ProductBiddingCategoryConstantService.GetProductBiddingCategoryConstant',
    index=0,
    containing_service=None,
    input_type=_GETPRODUCTBIDDINGCATEGORYCONSTANTREQUEST,
    output_type=google_dot_ads_dot_googleads_dot_v1_dot_resources_dot_product__bidding__category__constant__pb2._PRODUCTBIDDINGCATEGORYCONSTANT,
    serialized_options=b'\202\323\344\223\0027\0225/v1/{resource_name=productBiddingCategoryConstants/*}',
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTBIDDINGCATEGORYCONSTANTSERVICE)

DESCRIPTOR.services_by_name['ProductBiddingCategoryConstantService'] = _PRODUCTBIDDINGCATEGORYCONSTANTSERVICE

# @@protoc_insertion_point(module_scope)
