# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1alpha1/bill_of_materials.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.devtools.containeranalysis.v1alpha1 import package_vulnerability_pb2 as google_dot_devtools_dot_containeranalysis_dot_v1alpha1_dot_package__vulnerability__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/devtools/containeranalysis/v1alpha1/bill_of_materials.proto',
  package='google.devtools.containeranalysis.v1alpha1',
  syntax='proto3',
  serialized_options=b'\n%com.google.containeranalysis.v1alpha1P\001Z[google.golang.org/genproto/googleapis/devtools/containeranalysis/v1alpha1;containeranalysis\242\002\003GCA',
  serialized_pb=b'\nBgoogle/devtools/containeranalysis/v1alpha1/bill_of_materials.proto\x12*google.devtools.containeranalysis.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x46google/devtools/containeranalysis/v1alpha1/package_vulnerability.proto\"\xd7\x05\n\x0ePackageManager\x1a\x93\x02\n\x0c\x44istribution\x12\x0f\n\x07\x63pe_uri\x18\x01 \x01(\t\x12]\n\x0c\x61rchitecture\x18\x02 \x01(\x0e\x32G.google.devtools.containeranalysis.v1alpha1.PackageManager.Architecture\x12]\n\x0elatest_version\x18\x03 \x01(\x0b\x32\x45.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.Version\x12\x12\n\nmaintainer\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x1a\x81\x01\n\x08Location\x12\x0f\n\x07\x63pe_uri\x18\x01 \x01(\t\x12V\n\x07version\x18\x02 \x01(\x0b\x32\x45.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.Version\x12\x0c\n\x04path\x18\x03 \x01(\t\x1av\n\x07Package\x12\x0c\n\x04name\x18\x01 \x01(\t\x12]\n\x0c\x64istribution\x18\n \x03(\x0b\x32G.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution\x1as\n\x0cInstallation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12U\n\x08location\x18\x02 \x03(\x0b\x32\x43.google.devtools.containeranalysis.v1alpha1.PackageManager.Location\">\n\x0c\x41rchitecture\x12\x1c\n\x18\x41RCHITECTURE_UNSPECIFIED\x10\x00\x12\x07\n\x03X86\x10\x01\x12\x07\n\x03X64\x10\x02\x42\x8c\x01\n%com.google.containeranalysis.v1alpha1P\x01Z[google.golang.org/genproto/googleapis/devtools/containeranalysis/v1alpha1;containeranalysis\xa2\x02\x03GCAb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_devtools_dot_containeranalysis_dot_v1alpha1_dot_package__vulnerability__pb2.DESCRIPTOR,])



_PACKAGEMANAGER_ARCHITECTURE = _descriptor.EnumDescriptor(
  name='Architecture',
  full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Architecture',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARCHITECTURE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X86', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X64', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=882,
  serialized_end=944,
)
_sym_db.RegisterEnumDescriptor(_PACKAGEMANAGER_ARCHITECTURE)


_PACKAGEMANAGER_DISTRIBUTION = _descriptor.Descriptor(
  name='Distribution',
  full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpe_uri', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.cpe_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='architecture', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.architecture', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_version', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.latest_version', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maintainer', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.maintainer', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.url', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.description', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=511,
)

_PACKAGEMANAGER_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpe_uri', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Location.cpe_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Location.version', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Location.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=643,
)

_PACKAGEMANAGER_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Package.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distribution', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Package.distribution', index=1,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=645,
  serialized_end=763,
)

_PACKAGEMANAGER_INSTALLATION = _descriptor.Descriptor(
  name='Installation',
  full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Installation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.location', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=765,
  serialized_end=880,
)

_PACKAGEMANAGER = _descriptor.Descriptor(
  name='PackageManager',
  full_name='google.devtools.containeranalysis.v1alpha1.PackageManager',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_PACKAGEMANAGER_DISTRIBUTION, _PACKAGEMANAGER_LOCATION, _PACKAGEMANAGER_PACKAGE, _PACKAGEMANAGER_INSTALLATION, ],
  enum_types=[
    _PACKAGEMANAGER_ARCHITECTURE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=944,
)

_PACKAGEMANAGER_DISTRIBUTION.fields_by_name['architecture'].enum_type = _PACKAGEMANAGER_ARCHITECTURE
_PACKAGEMANAGER_DISTRIBUTION.fields_by_name['latest_version'].message_type = google_dot_devtools_dot_containeranalysis_dot_v1alpha1_dot_package__vulnerability__pb2._VULNERABILITYTYPE_VERSION
_PACKAGEMANAGER_DISTRIBUTION.containing_type = _PACKAGEMANAGER
_PACKAGEMANAGER_LOCATION.fields_by_name['version'].message_type = google_dot_devtools_dot_containeranalysis_dot_v1alpha1_dot_package__vulnerability__pb2._VULNERABILITYTYPE_VERSION
_PACKAGEMANAGER_LOCATION.containing_type = _PACKAGEMANAGER
_PACKAGEMANAGER_PACKAGE.fields_by_name['distribution'].message_type = _PACKAGEMANAGER_DISTRIBUTION
_PACKAGEMANAGER_PACKAGE.containing_type = _PACKAGEMANAGER
_PACKAGEMANAGER_INSTALLATION.fields_by_name['location'].message_type = _PACKAGEMANAGER_LOCATION
_PACKAGEMANAGER_INSTALLATION.containing_type = _PACKAGEMANAGER
_PACKAGEMANAGER_ARCHITECTURE.containing_type = _PACKAGEMANAGER
DESCRIPTOR.message_types_by_name['PackageManager'] = _PACKAGEMANAGER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PackageManager = _reflection.GeneratedProtocolMessageType('PackageManager', (_message.Message,), {

  'Distribution' : _reflection.GeneratedProtocolMessageType('Distribution', (_message.Message,), {
    'DESCRIPTOR' : _PACKAGEMANAGER_DISTRIBUTION,
    '__module__' : 'google.devtools.containeranalysis.v1alpha1.bill_of_materials_pb2'
    # @@protoc_insertion_point(class_scope:google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution)
    })
  ,

  'Location' : _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
    'DESCRIPTOR' : _PACKAGEMANAGER_LOCATION,
    '__module__' : 'google.devtools.containeranalysis.v1alpha1.bill_of_materials_pb2'
    # @@protoc_insertion_point(class_scope:google.devtools.containeranalysis.v1alpha1.PackageManager.Location)
    })
  ,

  'Package' : _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), {
    'DESCRIPTOR' : _PACKAGEMANAGER_PACKAGE,
    '__module__' : 'google.devtools.containeranalysis.v1alpha1.bill_of_materials_pb2'
    # @@protoc_insertion_point(class_scope:google.devtools.containeranalysis.v1alpha1.PackageManager.Package)
    })
  ,

  'Installation' : _reflection.GeneratedProtocolMessageType('Installation', (_message.Message,), {
    'DESCRIPTOR' : _PACKAGEMANAGER_INSTALLATION,
    '__module__' : 'google.devtools.containeranalysis.v1alpha1.bill_of_materials_pb2'
    # @@protoc_insertion_point(class_scope:google.devtools.containeranalysis.v1alpha1.PackageManager.Installation)
    })
  ,
  'DESCRIPTOR' : _PACKAGEMANAGER,
  '__module__' : 'google.devtools.containeranalysis.v1alpha1.bill_of_materials_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.containeranalysis.v1alpha1.PackageManager)
  })
_sym_db.RegisterMessage(PackageManager)
_sym_db.RegisterMessage(PackageManager.Distribution)
_sym_db.RegisterMessage(PackageManager.Location)
_sym_db.RegisterMessage(PackageManager.Package)
_sym_db.RegisterMessage(PackageManager.Installation)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
