# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/functions/v1beta2/operations.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/cloud/functions/v1beta2/operations.proto',
  package='google.cloud.functions.v1beta2',
  syntax='proto3',
  serialized_options=b'\n\"com.google.cloud.functions.v1beta2B\030FunctionsOperationsProtoP\001ZGgoogle.golang.org/genproto/googleapis/cloud/functions/v1beta2;functions',
  serialized_pb=b'\n/google/cloud/functions/v1beta2/operations.proto\x12\x1egoogle.cloud.functions.v1beta2\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xd3\x01\n\x18OperationMetadataV1Beta2\x12\x0e\n\x06target\x18\x01 \x01(\t\x12;\n\x04type\x18\x02 \x01(\x0e\x32-.google.cloud.functions.v1beta2.OperationType\x12%\n\x07request\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x12\n\nversion_id\x18\x04 \x01(\x03\x12/\n\x0bupdate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*i\n\rOperationType\x12\x19\n\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x43REATE_FUNCTION\x10\x01\x12\x13\n\x0fUPDATE_FUNCTION\x10\x02\x12\x13\n\x0f\x44\x45LETE_FUNCTION\x10\x03\x42\x89\x01\n\"com.google.cloud.functions.v1beta2B\x18\x46unctionsOperationsProtoP\x01ZGgoogle.golang.org/genproto/googleapis/cloud/functions/v1beta2;functionsb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])

_OPERATIONTYPE = _descriptor.EnumDescriptor(
  name='OperationType',
  full_name='google.cloud.functions.v1beta2.OperationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPERATION_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_FUNCTION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_FUNCTION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_FUNCTION', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=387,
  serialized_end=492,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONTYPE)

OperationType = enum_type_wrapper.EnumTypeWrapper(_OPERATIONTYPE)
OPERATION_UNSPECIFIED = 0
CREATE_FUNCTION = 1
UPDATE_FUNCTION = 2
DELETE_FUNCTION = 3



_OPERATIONMETADATAV1BETA2 = _descriptor.Descriptor(
  name='OperationMetadataV1Beta2',
  full_name='google.cloud.functions.v1beta2.OperationMetadataV1Beta2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='google.cloud.functions.v1beta2.OperationMetadataV1Beta2.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='google.cloud.functions.v1beta2.OperationMetadataV1Beta2.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='google.cloud.functions.v1beta2.OperationMetadataV1Beta2.request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version_id', full_name='google.cloud.functions.v1beta2.OperationMetadataV1Beta2.version_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='google.cloud.functions.v1beta2.OperationMetadataV1Beta2.update_time', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=385,
)

_OPERATIONMETADATAV1BETA2.fields_by_name['type'].enum_type = _OPERATIONTYPE
_OPERATIONMETADATAV1BETA2.fields_by_name['request'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_OPERATIONMETADATAV1BETA2.fields_by_name['update_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['OperationMetadataV1Beta2'] = _OPERATIONMETADATAV1BETA2
DESCRIPTOR.enum_types_by_name['OperationType'] = _OPERATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OperationMetadataV1Beta2 = _reflection.GeneratedProtocolMessageType('OperationMetadataV1Beta2', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONMETADATAV1BETA2,
  '__module__' : 'google.cloud.functions.v1beta2.operations_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.functions.v1beta2.OperationMetadataV1Beta2)
  })
_sym_db.RegisterMessage(OperationMetadataV1Beta2)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
