# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.cloud.osconfig.v1beta import guest_policies_pb2 as google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2
from google.cloud.osconfig.v1beta import patch_deployments_pb2 as google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2
from google.cloud.osconfig.v1beta import patch_jobs_pb2 as google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class OsConfigServiceStub(object):
  """OS Config API

  The OS Config service is a server-side component that you can use to
  manage package installations and patch jobs for virtual machine instances.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExecutePatchJob = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/ExecutePatchJob',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ExecutePatchJobRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.PatchJob.FromString,
        )
    self.GetPatchJob = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/GetPatchJob',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.GetPatchJobRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.PatchJob.FromString,
        )
    self.CancelPatchJob = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/CancelPatchJob',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.CancelPatchJobRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.PatchJob.FromString,
        )
    self.ListPatchJobs = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/ListPatchJobs',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ListPatchJobsRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ListPatchJobsResponse.FromString,
        )
    self.ListPatchJobInstanceDetails = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/ListPatchJobInstanceDetails',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsResponse.FromString,
        )
    self.CreatePatchDeployment = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/CreatePatchDeployment',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.CreatePatchDeploymentRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.PatchDeployment.FromString,
        )
    self.GetPatchDeployment = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/GetPatchDeployment',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.GetPatchDeploymentRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.PatchDeployment.FromString,
        )
    self.ListPatchDeployments = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/ListPatchDeployments',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.ListPatchDeploymentsRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.ListPatchDeploymentsResponse.FromString,
        )
    self.DeletePatchDeployment = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/DeletePatchDeployment',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.DeletePatchDeploymentRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.CreateGuestPolicy = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/CreateGuestPolicy',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.CreateGuestPolicyRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.GuestPolicy.FromString,
        )
    self.GetGuestPolicy = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/GetGuestPolicy',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.GetGuestPolicyRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.GuestPolicy.FromString,
        )
    self.ListGuestPolicies = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/ListGuestPolicies',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.ListGuestPoliciesRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.ListGuestPoliciesResponse.FromString,
        )
    self.UpdateGuestPolicy = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/UpdateGuestPolicy',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.UpdateGuestPolicyRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.GuestPolicy.FromString,
        )
    self.DeleteGuestPolicy = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/DeleteGuestPolicy',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.DeleteGuestPolicyRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.LookupEffectiveGuestPolicy = channel.unary_unary(
        '/google.cloud.osconfig.v1beta.OsConfigService/LookupEffectiveGuestPolicy',
        request_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.LookupEffectiveGuestPolicyRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.EffectiveGuestPolicy.FromString,
        )


class OsConfigServiceServicer(object):
  """OS Config API

  The OS Config service is a server-side component that you can use to
  manage package installations and patch jobs for virtual machine instances.
  """

  def ExecutePatchJob(self, request, context):
    """Patch VM instances by creating and running a patch job.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPatchJob(self, request, context):
    """Get the patch job. This can be used to track the progress of an
    ongoing patch job or review the details of completed jobs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CancelPatchJob(self, request, context):
    """Cancel a patch job. The patch job must be active. Canceled patch jobs
    cannot be restarted.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPatchJobs(self, request, context):
    """Get a list of patch jobs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPatchJobInstanceDetails(self, request, context):
    """Get a list of instance details for a given patch job.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePatchDeployment(self, request, context):
    """Create an OS Config patch deployment.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPatchDeployment(self, request, context):
    """Get an OS Config patch deployment.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPatchDeployments(self, request, context):
    """Get a page of OS Config patch deployments.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePatchDeployment(self, request, context):
    """Delete an OS Config patch deployment.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateGuestPolicy(self, request, context):
    """Create an OS Config guest policy.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGuestPolicy(self, request, context):
    """Get an OS Config guest policy.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListGuestPolicies(self, request, context):
    """Get a page of OS Config guest policies.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateGuestPolicy(self, request, context):
    """Update an OS Config guest policy.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteGuestPolicy(self, request, context):
    """Delete an OS Config guest policy.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LookupEffectiveGuestPolicy(self, request, context):
    """Lookup the effective guest policy that applies to a VM instance. This
    lookup merges all policies that are assigned to the instance ancestry.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OsConfigServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExecutePatchJob': grpc.unary_unary_rpc_method_handler(
          servicer.ExecutePatchJob,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ExecutePatchJobRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.PatchJob.SerializeToString,
      ),
      'GetPatchJob': grpc.unary_unary_rpc_method_handler(
          servicer.GetPatchJob,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.GetPatchJobRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.PatchJob.SerializeToString,
      ),
      'CancelPatchJob': grpc.unary_unary_rpc_method_handler(
          servicer.CancelPatchJob,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.CancelPatchJobRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.PatchJob.SerializeToString,
      ),
      'ListPatchJobs': grpc.unary_unary_rpc_method_handler(
          servicer.ListPatchJobs,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ListPatchJobsRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ListPatchJobsResponse.SerializeToString,
      ),
      'ListPatchJobInstanceDetails': grpc.unary_unary_rpc_method_handler(
          servicer.ListPatchJobInstanceDetails,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__jobs__pb2.ListPatchJobInstanceDetailsResponse.SerializeToString,
      ),
      'CreatePatchDeployment': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePatchDeployment,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.CreatePatchDeploymentRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.PatchDeployment.SerializeToString,
      ),
      'GetPatchDeployment': grpc.unary_unary_rpc_method_handler(
          servicer.GetPatchDeployment,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.GetPatchDeploymentRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.PatchDeployment.SerializeToString,
      ),
      'ListPatchDeployments': grpc.unary_unary_rpc_method_handler(
          servicer.ListPatchDeployments,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.ListPatchDeploymentsRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.ListPatchDeploymentsResponse.SerializeToString,
      ),
      'DeletePatchDeployment': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePatchDeployment,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_patch__deployments__pb2.DeletePatchDeploymentRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'CreateGuestPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.CreateGuestPolicy,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.CreateGuestPolicyRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.GuestPolicy.SerializeToString,
      ),
      'GetGuestPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.GetGuestPolicy,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.GetGuestPolicyRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.GuestPolicy.SerializeToString,
      ),
      'ListGuestPolicies': grpc.unary_unary_rpc_method_handler(
          servicer.ListGuestPolicies,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.ListGuestPoliciesRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.ListGuestPoliciesResponse.SerializeToString,
      ),
      'UpdateGuestPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGuestPolicy,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.UpdateGuestPolicyRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.GuestPolicy.SerializeToString,
      ),
      'DeleteGuestPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteGuestPolicy,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.DeleteGuestPolicyRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'LookupEffectiveGuestPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.LookupEffectiveGuestPolicy,
          request_deserializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.LookupEffectiveGuestPolicyRequest.FromString,
          response_serializer=google_dot_cloud_dot_osconfig_dot_v1beta_dot_guest__policies__pb2.EffectiveGuestPolicy.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.cloud.osconfig.v1beta.OsConfigService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
